[app]
title = PseudoPet
package.name = pseudopet
package.domain = org.beezi
# main.py sourcepath
source.dir = .
source.include_exts = py,png,jpg,kv,atlas,ogg,ttf
source.exclude_dirs = tests,test,bin,venv,.venv,__pycache__,.bak1,.bak
version = 0.85
requirements = python3==3.10.12,hostpython3==3.10.12,pygame,pyjnius,plyer,websockets,android,kivy
presplash.filename = %(source.dir)s/pseudopet.png
icon.filename = %(source.dir)s/pseudopet.png
orientation = portrait
osx.python_version = 3
osx.kivy_version = 1.9.1
fullscreen = True
android.presplash_color = black
android.permissions = android.permission.INTERNET, android.permission.ACCESS_NETWORK_STATE, android.permission.ACCESS_WIFI_STATE, android.permission.WAKE_LOCK, android.permission.POST_NOTIFICATIONS, android.permission.SCHEDULE_EXACT_ALARM, android.permission.VIBRATE
android.api = 34
android.minapi = 21
android.accept_sdk_license = True
android.wakelock = True
android.logcat_pid_only = True
android.archs = arm64-v8a,armeabi-v7a
#android.extra_manifest_xml = manifest_extra.xml
#android.add_src = src
[buildozer]
log_level = 2
warn_on_root = 1
#android.sdk = 34
#android.ndk = 26
#android.ndk_api = 21
#android.private_storage = True
#android.ndk_path =
#android.sdk_path =
#android.ant_path =
#android.skip_update = False
#android.entrypoint = org.kivy.android.PythonActivity
#android.activity_class_name = org.kivy.android.PythonActivity
#android.extra_manifest_xml = ./src/android/manifest_extra.xml
#android.extra_manifest_application_arguments = ./src/android/extra_manifest_application_arguments.xml
#android.service_class_name = org.kivy.android.PythonService
#android.apptheme = "@android:style/Theme.NoTitleBar"
#android.whitelist =
#android.whitelist_src =
#android.blacklist_src =
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar
#android.add_aars =
#android.add_assets =
#android.add_resources =
#android.gradle_dependencies =
#android.enable_androidx = True
#android.add_compile_options = "sourceCompatibility = 1.8", "targetCompatibility = 1.8"
#android.add_gradle_repositories =
#android.add_packaging_options =
#android.add_activities = com.example.ExampleActivity
#android.ouya.category = GAME
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png
#android.manifest.intent_filters =
#android.res_xml = PATH_TO_FILE,
#android.manifest.launch_mode = standard
#android.manifest.orientation = fullSensor
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_arm64_v8a = libs/android-v8/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so
#android.meta_data =
#android.library_references =
#android.uses_library =
#android.logcat_filters = *:S python:D
#android.adb_args = -H host.docker.internal
#android.copy_libs = 1
#android.numeric_version = 1
#android.allow_backup = True
#android.backup_rules =
#android.manifest_placeholders = [:]
#android.no-byte-compile-python = False
#android.release_artifact = aab
#android.debug_artifact = apk
#p4a.url =
#p4a.fork = kivy
#p4a.branch = master
#p4a.commit = HEAD
#p4a.source_dir =
#p4a.local_recipes =
#p4a.hook =
#p4a.bootstrap = sdl2
#p4a.port =
#p4a.setup_py = false
#p4a.extra_args =
#ios.kivy_ios_url = https://github.com/kivy/kivy-ios
#ios.kivy_ios_branch = master
#ios.ios_deploy_dir = ../ios_deploy
#ios.ios_deploy_url = https://github.com/phonegap/ios-deploy
#ios.ios_deploy_branch = 1.10.0
#ios.codesign.allowed = false
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"
#ios.codesign.development_team.debug = <hexstring>
#ios.codesign.release = %(ios.codesign.debug)s
#ios.codesign.development_team.release = <hexstring>
#ios.manifest.app_url =
#ios.manifest.display_image_url =
#ios.manifest.full_size_image_url =
#build_dir = ./.buildozer
#bin_dir = ./bin
