# -*- coding: utf-8 -*-
# sprites.py — von build_pseudopet.py erzeugt am 2026-09-05 22:12
# "X" = voller Pixel, "O" = 50%-Dither (Schattierung)

SPRITES = {
    # === EIER ===
    "egg_dot": [
        r"X...XXX...X",
        r"X..XXXXX..X",
        r".XXXXXXXXX.",
        r".XXXXXXXXX.",
        r".XXXXX..XX.",
        r"XXXXXX..XXX",
        r"XXXXXX..XXX",
        r"XXXXXXXXXXX",
        r"XXX.XXXXXXX",
        r"XXX.XXXXXXX",
        r"XXXXXX..XXX",
        r".XXXXXXXXX.",
        r".XXXXXXXXX.",
        r"X.XXXXXXX.X",
        r"...XXXXX...",
    ],
    "egg_stripe": [
        r"....XXXX....",
        r"...XXXX.X...",
        r"..XXXX.XXX..",
        r".XXXX.XXXX..",
        r".XXX.XXXX.X.",
        r"XXX.XXXX.XXX",
        r"XX.XXXX.XXXX",
        r"X.XXXX.XXXX.",
        r".XXXX.XXXX.X",
        r"XXXX.XXXX.XX",
        r"XXX.XXXX.XXX",
        r".X.XXXX.XXX.",
        r".XXXXX.XXXX.",
        r"..XXX.XXXX..",
        r"...X.XXXX...",
    ],
    "egg_clean": [
        r"....XXXX....",
        r"...XXXXXX...",
        r"..XXXXXXXX..",
        r".XXXXXXXXXX.",
        r".XXXXXXXXXX.",
        r"XXXXXXXXXXXX",
        r"XXXXXXXXXXXX",
        r"XXXXXXXXXXXX",
        r"XXXXXXXXXXXX",
        r"XXXXXXXXXXXX",
        r"XXXXXXXXXXXX",
        r".XXXXXXXXXX.",
        r".XXXXXXXXXX.",
        r"..XXXXXXXX..",
        r"...XXXXXX...",
    ],

    # === ZWEIG SPIKE ===
    "spike_baby": [
        r"X.XX.X",
        r".XXXX.",
        r"X.XX.X",
        r"XXXXXX",
        r".X..X.",
        r"..XX..",
        r".X..X.",
    ],
    "spike_child": [
        r"X..XX..X",
        r".XXXXXX.",
        r".X.XX.X.",
        r"XX.XX.XX",
        r"XXXXXXXX",
        r".XX..XX.",
        r"..XXXX..",
        r".XX..XX.",
        r"X......X",
    ],
    "spike_teen": [
        r"X..XX..X",
        r"XX.XX.XX",
        r".XXXXXX.",
        r"XX.XX.XX",
        r"X..XX..X",
        r"XXXXXXXX",
        r".XX..XX.",
        r".XXXXXX.",
        r".XXXXXX.",
        r"X......X",
        r"XX....XX",
    ],
    "spike_adult": [
        r".X..XX..X.",
        r"XXX.XX.XXX",
        r"..XXXXXX..",
        r".XX.XX.XX.",
        r".X..XX..X.",
        r".XXXXXXXX.",
        r"..XX..XX..",
        r"..XXXXXX..",
        r".XX....XX.",
        r"X...XX...X",
        r"XX......XX",
    ],
    "spike_premium": [
        r"X.X..XXXX..X.X",
        r".XXXX.XX.XXXX.",
        r"....XXXXXX....",
        r"..XXXXXXXXXX..",
        r".XXX.XXXX.XXX.",
        r".XXXXXXXXXXXX.",
        r"XXXXXXXXXXXXXX",
        r"XXXX.XXXX.XXXX",
        r".XXXXXXXXXXXX.",
        r"..XXX....XXX..",
        r".XXXX....XXXX.",
    ],

    # === ZWEIG STRIPE ===
    "stripe_baby": [
        r"..X.X.",
        r"...X..",
        r"..XX..",
        r".XXXX.",
        r"X.XX.X",
        r"XXXXXX",
        r".X..X.",
        r"..XX..",
        r".X..X.",
    ],
    "stripe_child": [
        r"XXX..XXX",
        r".X.XX.X.",
        r"...XX...",
        r"..XXXX..",
        r".X.XX.X.",
        r"XX.XX.XX",
        r"XXXXXXXX",
        r".XX..XX.",
        r"..XXXX..",
        r".XX..XX.",
        r"X......X",
    ],
    "stripe_teen": [
        r".XXXXXX.",
        r"X..XX..X",
        r"XX.XX.XX",
        r"...XX...",
        r"XXXXXXXX",
        r"X.XXXX.X",
        r"X..XX..X",
        r"XXXXXXXX",
        r".XX..XX.",
        r".XXXXXX.",
        r"X..XX..X",
        r"XX....XX",
    ],
    "stripe_adult": [
        r".XXXXXXXX.",
        r"X...XX...X",
        r"XXX.XX.XXX",
        r"....XX....",
        r".XXXXXXXX.",
        r".X.XXXX.X.",
        r".X..XX..X.",
        r".XXXXXXXX.",
        r"..XXXXXX..",
        r".XX....XX.",
        r"X...XX...X",
        r"XX......XX",
    ],
    "stripe_premium": [
        r"..XXXXXXXX..",
        r".X...XX...X.",
        r"XXX.XXXX.XXX",
        r".....XX.....",
        r"..XXXXXXXX..",
        r".XX.XXXX.XX.",
        r".XX..XX..XX.",
        r"..XXXXXXXX..",
        r"...XX..XX...",
        r".XXXXXXX...X",
        r".XXXX....XX.",
        r"..XXXXXXXX..",
    ],

    # === ZWEIG CLEAN ===
    "clean_baby": [
        r"...XX...",
        r"..XXXX..",
        r".X.XX.X.",
        r".XXXXXX.",
        r"X.X..X.X",
        r"...XX...",
        r"..X..X..",
    ],
    "clean_child": [
        r"....XX....",
        r"...XXXX...",
        r"..X.XX.X..",
        r".XX.XX.XX.",
        r".XXXXXXXX.",
        r"X.XX..XX.X",
        r"X..XXXX..X",
        r"..X....X..",
        r".X......X.",
    ],
    "clean_teen": [
        r"....XXXX....",
        r"..XXXXXXXX..",
        r"..X..XX..X..",
        r"..X.XXXX.X..",
        r"..XXXXXXXX..",
        r".X.XX..XX.X.",
        r"XX..XXXX..XX",
        r"...X....X...",
        r".XXX....XXX.",
    ],
    "clean_adult": [
        r".....XX.....",
        r"....XXXX....",
        r"..XXXXXXXX..",
        r"..X..XX..X..",
        r"..X.XXXX.X..",
        r"..XXXXXXXX..",
        r".X.XX..XX.X.",
        r"XX..XXXX..XX",
        r"X..XX..XX..X",
        r"...X....X...",
        r".XXX....XXX.",
    ],
    "clean_premium": [
        r"...XX.XX.XX...",
        r".....XXXX.....",
        r"XX.XXXXXXXX.XX",
        r"XXXX..XX..XXXX",
        r"X..X.XXXX.X..X",
        r"X..XXXXXXXX..X",
        r"..XXXX..XXXX..",
        r".XX..XXXX..XX.",
        r"XX..XX..XX..XX",
        r"X...XX..XX...X",
        r"..XXXX..XXXX..",
    ],

    # === ZWEIG FLAME ===
    "flame_baby": [
        r"X..X..X",
        r"X.XXX.X",
        r".XXXXX.",
        r"XX.X.XX",
        r"XXXXXXX",
        r".XXXXX.",
        r"..X.X..",
        r".X...X.",
    ],
    "flame_child": [
        r"X...X...X",
        r"X.XXXXX.X",
        r".XXXXXXX.",
        r".XXXXXXX.",
        r"XX.XXX.XX",
        r"XXXXXXXXX",
        r"XXX.X.XXX",
        r".XXXXXXX.",
        r".X..X..X.",
    ],
    "flame_teen": [
        r"X....X....X",
        r"X.XXXXXXX.X",
        r"XX.XXXXX.XX",
        r".XXXXXXXXX.",
        r"XXX.XXX.XXX",
        r"XXXXXXXXXXX",
        r"XXXX.X.XXXX",
        r".XXXXXXXXX.",
        r"..XXXXXXX..",
        r".X.X.X.X.X.",
        r"..X.....X..",
    ],
    "flame_adult": [
        r"....XXXXX....",
        r"...XXXXXXX...",
        r"..XX.XXX.XX..",
        r".XXX.XXX.XXX.",
        r".XXXXXXXXXXX.",
        r".XXX.....XXX.",
        r".XXXX...XXXX.",
        r"..XXXXXXXXX..",
        r"...XXXXXXX...",
        r"..XXXXXXXXX..",
        r".XX.XXXXX.XX.",
        r"..X..XXX..X..",
        r".X....X....X.",
    ],
    "flame_premium": [
        r"....XXXXXXX....",
        r"...XXXXXXXXX...",
        r"..X...XXX...X..",
        r".XXXXXXXXXXXXX.",
        r".XXXXXXXXXXXXX.",
        r".XXXX.XXX.XXXX.",
        r".XXXXXXXXXXXXX.",
        r"XX.XXXXXXXXX.XX",
        r"XXXXXXXXXXXXXXX",
        r"XX.XXXXXXXXX.XX",
        r".XXXXXXXXXXXXX.",
        r"..XXXXXXXXXXX..",
        r"...XXXXXXXXX...",
    ],
    # === ZWEIG LEAF ===
    "leaf_baby": [
        r".X...X.",
        r"XX.X.XX",
        r".XXXXX.",
        r"XX.X.XX",
        r"XXXXXXX",
        r".XXXXX.",
        r"..X.X..",
    ],
    "leaf_child": [
        r"..X.X.X..",
        r".XXXXXXX.",
        r"XX.XXX.XX",
        r"XXXXXXXXX",
        r"XXX.X.XXX",
        r".XXXXXXX.",
        r"..X.X.X..",
        r".X.....X.",
    ],
    "leaf_teen": [
        r"..X..X..X..",
        r".XX.XXX.XX.",
        r".XXXXXXXXX.",
        r"XX.XXXXX.XX",
        r"XXXXXXXXXXX",
        r"XXXX.X.XXXX",
        r".XXXXXXXXX.",
        r"..XXXXXXX..",
        r".X.X.X.X.X.",
    ],
    "leaf_adult": [
        r"..X...X...X..",
        r".XX..XXX..XX.",
        r".XXXXXXXXXXX.",
        r"XX.XXXXXXX.XX",
        r"XXXXXXXXXXXXX",
        r"XXXXX.X.XXXXX",
        r"XXXXXXXXXXXXX",
        r".XXXXXXXXXXX.",
        r"..XX.XXX.XX..",
        r".X.X..X..X.X.",
        r"..X.......X..",
    ],
    "leaf_premium": [
        r"..X....X....X..",
        r".XX..XXXXX..XX.",
        r".XXXXXXXXXXXXX.",
        r"XXX.XXXXXXX.XXX",
        r"XXXXXXXXXXXXXXX",
        r"XXXX..XXX..XXXX",
        r"XXXXXXXXXXXXXXX",
        r"XXXXX.XXX.XXXXX",
        r".XXXXXXXXXXXXX.",
        r"..XX.XXXXX.XX..",
        r".X.X..X.X..X.X.",
        r".X..X.....X..X.",
        r".....XX.XX.....",
    ],

    # === ZWEIG AQUA ===
    "aqua_baby": [
        r"..XXX..",
        r".XXXXX.",
        r"XX.X.XX",
        r"XXXXXXX",
        r"XXXXXXX",
        r".XXXXX.",
        r"..X.X..",
        r".X...X.",
    ],
    "aqua_child": [
        r"...XXX...",
        r"..XXXXX..",
        r".XX.X.XX.",
        r"XXXXXXXXX",
        r"XXX.X.XXX",
        r"XXXXXXXXX",
        r".XXXXXXX.",
        r"..X.X.X..",
        r".X..X..X.",
    ],
    "aqua_teen": [
        r"....XXX....",
        r"...XXXXX...",
        r"..XX.X.XX..",
        r".XXXXXXXXX.",
        r"XXX.XXX.XXX",
        r"XXXXXXXXXXX",
        r"XXXX.X.XXXX",
        r".XXXXXXXXX.",
        r"..XXXXXXX..",
        r"..X.X.X.X..",
        r".X.......X.",
    ],
    "aqua_adult": [
        r".....XXX.....",
        r"...XXXXXXX...",
        r"..XX.XXX.XX..",
        r".XXXXXXXXXXX.",
        r"XXXX.XXX.XXXX",
        r"XXXXXXXXXXXXX",
        r"XXX..XXX..XXX",
        r"XXXXXXXXXXXXX",
        r".XX.XXXXX.XX.",
        r"..X.XXXXX.X..",
        r".X.X.X.X.X.X.",
        r"...X..X..X...",
    ],
    "aqua_premium": [
        r".X..X.XX.X..X.",
        r"..XXXXXXXXXX..",
        r".XXXXXXXXXXXX.",
        r".XX..XXXX..XX.",
        r"XXXXXXXXXXXXXX",
        r"XXX.XXXXXX.XXX",
        r"XXXXXXXXXXXXXX",
        r".XX.XXXXXX.XX.",
        r"..X.X.XX.X.X..",
        r".X..X.XX.X..X.",
        r"X..X..XX..X..X",
    ],

    # === ZWEIG DARK ===
    "dark_baby": [
        r"X......X",
        r".X....X.",
        r".XXXXXX.",
        r".XX..XX.",
        r".XXXXXX.",
        r"XXXXXXXX",
        r".XX..XX.",
        r"..X..X..",
    ],
    "dark_child": [
        r"X......X",
        r".X.XX.X.",
        r".XXXXXX.",
        r"XXX..XXX",
        r"XXXXXXXX",
        r"XX.XX.XX",
        r".XXXXXX.",
        r"..X..X..",
        r".X....X.",
    ],
    "dark_teen": [
        r"X...XX...X",
        r".X.XXXX.X.",
        r".XXXXXXXX.",
        r"XXX.XX.XXX",
        r"XXXXXXXXXX",
        r"XX.XXXX.XX",
        r"XXX....XXX",
        r".XXXXXXXX.",
        r"..X.XX.X..",
        r".X..XX..X.",
    ],
    "dark_adult": [
        r"................",
        r"......X..X......",
        r"......X..X......",
        r"...X.XX..XX.X...",
        r"..XXXXXXXXXXXX..",
        r".XXXXX.XX.XXXXX.",
        r".XXXXXXXXXXXXXX.",
        r"XXXXXXX..XXXXXXX",
        r"XX.XX..XX..XX.XX",
        r"X..X........X..X",
        r"................",
    ],
    "dark_premium": [
        r".....X.X.X.X.....",
        r".....XXXXXXX.....",
        r".................",
        r"......X...X......",
        r"......X...X......",
        r"...X.XXX.XXX.X...",
        r"..XXXXXXXXXXXXX..",
        r".XXXXX.XXX.XXXXX.",
        r".XXXXXXXXXXXXXXX.",
        r"XXXXXXX...XXXXXXX",
        r"XX.XX..XXX..XX.XX",
        r"X..X.........X..X",
    ],
    "plush_baby": [
        r"..XXXX..",
        r".XXXXXX.",
        r".X.XX.X.",
        r"XXXXXXXX",
        r"XXXXXXXX",
        r".XXXXXX.",
        r"..X..X..",
        r".X....X.",
    ],
    "plush_child": [
        r"..XX..XX..",
        r".XXXXXXXX.",
        r".XXXXXXXX.",
        r".XX.XX.XX.",
        r".XXXXXXXX.",
        r"XXXXXXXXXX",
        r".XXXXXXXX.",
        r"..XXXXXX..",
        r".X..XX..X.",
    ],
    "plush_teen": [
        r"..XXX.XXX..",
        r".XXXXXXXXX.",
        r".XXXXXXXXX.",
        r".XX.XXX.XX.",
        r".XXXXXXXXX.",
        r"XXXXXXXXXXX",
        r".XXXXXXXXX.",
        r"..XXXXXXX..",
        r"..X.XXX.X..",
        r".XX..X..XX.",
    ],
    "plush_adult": [
        r"...XXXXXXX...",
        r".XXXXXXXXXXX.",
        r".XXXXXXXXXXX.",
        r".XXX.XXX.XXX.",
        r".XXXXXXXXXXX.",
        r"XXXXXX.XXXXXX",
        r"XXXXXXXXXXXXX",
        r"XX.XXXXXXX.XX",
        r".XXXXXXXXXXX.",
        r".XXXXXXXXXXX.",
        r"..XXX...XXX..",
        r".XXXX...XXXX.",
    ],
    "plush_premium": [
        r"..X....X....X..",
        r"...XXXXXXXXX...",
        r"..XXXXXXXXXXX..",
        r".XXXXXXXXXXXXX.",
        r".XXXX.XXX.XXXX.",
        r".XXXXXXXXXXXXX.",
        r"XXXXXXXXXXXXXXX",
        r"XXXXX.XXX.XXXXX",
        r".XXXXXXXXXXXXX.",
        r".XXXXXXXXXXXXX.",
        r"..XXX.XXX.XXX..",
        r"..XX...X...XX..",
        r".XXXX..X..XXXX.",
    ],
    "imp_baby": [
        r".X....X.",
        r".XX..XX.",
        r".XXXXXX.",
        r".X.XX.X.",
        r"XXXXXXXX",
        r".XXXXXX.",
        r"..XXXX..",
        r".X....X.",
    ],
    "imp_child": [
        r".XX....XX.",
        r".XXXXXXXX.",
        r".XX.XX.XX.",
        r".XXXXXXXX.",
        r"XXXXXXXXXX",
        r"XXX.XX.XXX",
        r".XXXXXXXX.",
        r"..XXXXXX..",
        r".X......X.",
    ],
    "imp_teen": [
        r".X.......X.",
        r".XX.....XX.",
        r".XXXXXXXXX.",
        r".XX.XXX.XX.",
        r".XXXXXXXXX.",
        r"XXXXXXXXXXX",
        r"XX.XX.XX.XX",
        r".XXXXXXXXX.",
        r"..XXXXXXX..",
        r".XX.....XX.",
    ],
    "imp_adult": [
        r".X.........X.",
        r".XX.......XX.",
        r".XXXXXXXXXXX.",
        r".XXXXXXXXXXX.",
        r".XX.XXXXX.XX.",
        r".XXXXXXXXXXX.",
        r"XXXXXXXXXXXXX",
        r"XXXX.XXX.XXXX",
        r"XXXXXXXXXXXXX",
        r".XXXXXXXXXXX.",
        r".XX.XXXXX.XX.",
        r".X.........X.",
    ],
    "imp_premium": [
        r"X....XX.XX....X",
        r".XXXXXXXXXXXXX.",
        r".XXXXXXXXXXXXX.",
        r".XXXXXXXXXXXXX.",
        r".XXX.XXXXX.XXX.",
        r".XXXXXXXXXXXXX.",
        r"XXXXXXXXXXXXXXX",
        r".XX.XXX.XXX.XX.",
        r"XXXXXXXXXXXXXXX",
        r".XXXXXXXXXXXXX.",
        r".XXXXXXXXXXXXX.",
        r".XX....X....XX.",
        r"X.....XXX.....X",
    ],
    "nimbus_baby": [
        r".XX..XX.",
        r".XXXXXX.",
        r"XXXXXXXX",
        r"XX.XX.XX",
        r"XXXXXXXX",
        r".XXXXXX.",
        r"..XXXX..",
        r".X.XX.X.",
    ],
    "nimbus_child": [
        r".XX....XX.",
        r".XXXXXXXX.",
        r"XXXXXXXXXX",
        r"XX.XXXX.XX",
        r"XXXXXXXXXX",
        r".XXXXXXXX.",
        r"..XXXXXX..",
        r".XX.XX.XX.",
        r".X..XX..X.",
    ],
    "nimbus_teen": [
        r"..X..X..X..",
        r".XXXXXXXXX.",
        r".X.X.X.X.X.",
        r".XXXXXXXXX.",
        r".XX.X.X.XX.",
        r"XXXXXXXXXXX",
        r".XXXXXXXXX.",
        r"..XX.X.XX..",
        r".X.XXXXX.X.",
        r"..X..X..X..",
    ],
    "nimbus_adult": [
        r"..X.......X..",
        r".XX.......XX.",
        r".XXXXXXXXXXX.",
        r".XXXXXXXXXXX.",
        r".XX.XXXXX.XX.",
        r".XXXXXXXXXXX.",
        r"XXXXXXXXXXXXX",
        r".XXXXXXXXXXX.",
        r".XXXXXXXXXXX.",
        r".XXXXXXXXXXX.",
        r"..XX.XXX.XX..",
        r".X...XXX...X.",
    ],
    "nimbus_premium": [
        r"..X..XXXXX..X..",
        r".XXXXXXXXXXXXX.",
        r".XXXXXXXXXXXXX.",
        r".XXXXXXXXXXXXX.",
        r".XXX.XXXXX.XXX.",
        r".XXXXXXXXXXXXX.",
        r"XXXXXXXXXXXXXXX",
        r"XXXX.X.X.X.XXXX",
        r"XXXXXXXXXXXXXXX",
        r".XXXXXXXXXXXXX.",
        r".XXXXXXXXXXXXX.",
        r"..XXX..X..XXX..",
        r".X....XXX....X.",
    ],
    "nova_baby": [
        r"..XXX..",
        r".XXXXX.",
        r"XX.X.XX",
        r"XXXXXXX",
        r".XXXXX.",
        r"..X.X..",
        r".X...X.",
    ],
    "nova_child": [
        r".X..X..X.",
        r"..XXXXX..",
        r".XXXXXXX.",
        r".XX.X.XX.",
        r"XXXXXXXXX",
        r".XXXXXXX.",
        r"..XXXXX..",
        r"..X.X.X..",
        r".X.....X.",
    ],
    "nova_teen": [
        r".X...X...X.",
        r"..X.XXX.X..",
        r".XXXXXXXXX.",
        r".XXX.X.XXX.",
        r"XXXXXXXXXXX",
        r".XXXXXXXXX.",
        r"..XXXXXXX..",
        r".XX.XXX.XX.",
        r"..X..X..X..",
        r".X..X.X..X.",
        r".X.......X.",
    ],
    "nova_adult": [
        r".X....X....X.",
        r"..X..XXX..X..",
        r".XXXXXXXXXXX.",
        r".XXXX.X.XXXX.",
        r"XXXXXXXXXXXXX",
        r".XXXXXXXXXXX.",
        r"..XXXXXXXXX..",
        r".XXX.XXX.XXX.",
        r"..X..XXX..X..",
        r".X..X.X.X..X.",
        r".X...X.X...X.",
        r"..X.......X..",
    ],
    "nova_premium": [
        r".X.....X.....X.",
        r"..X...XXX...X..",
        r"...X.XXXXX.X...",
        r".XXXXXXXXXXXXX.",
        r".XXXXX.X.XXXXX.",
        r"XXXXXXXXXXXXXXX",
        r".XXXXXXXXXXXXX.",
        r"..XXXXXXXXXXX..",
        r".XXXX.XXX.XXXX.",
        r"...X..XXX..X...",
        r"..X..X.X.X..X..",
        r".X..X..X..X..X.",
        r".X.....X.....X.",
    ],
    "volt_baby": [
        r".X...X.",
        r"XX.X.XX",
        r".XXXXX.",
        r"XXXXXXX",
        r".X.X.X.",
        r"..X.X..",
        r".X...X.",
    ],
    "volt_child": [
        r".X.....X.",
        r"XX.XXX.XX",
        r".XXXXXXX.",
        r"XXXXXXXXX",
        r"XX.XXX.XX",
        r".XXXXXXX.",
        r".X.XXX.X.",
        r"..X.X.X..",
        r".X.....X.",
    ],
    "volt_teen": [
        r".X...X...X.",
        r"XX.XXXXX.XX",
        r".XXXXXXXXX.",
        r"XXXXXXXXXXX",
        r"XX.XXXXX.XX",
        r".XXXXXXXXX.",
        r"XX.X.X.X.XX",
        r".XX.XXX.XX.",
        r"..X..X..X..",
        r".X..X.X..X.",
        r"X...X.X...X",
    ],
    "volt_adult": [
        r".X....X....X.",
        r"XX.XXXXXXX.XX",
        r".XXXXXXXXXXX.",
        r"XXXXXXXXXXXXX",
        r"XX.XXXXXXX.XX",
        r".XXXXXXXXXXX.",
        r"XXX.XXXXX.XXX",
        r".XX.XXXXX.XX.",
        r"..X.XXXXX.X..",
        r".X..X.X.X..X.",
        r"X..X..X..X..X",
    ],
    "volt_premium": [
        r".X.....X.....X.",
        r"XX.XXXXXXXXX.XX",
        r".XXXXXXXXXXXXX.",
        r"XXXXXXXXXXXXXXX",
        r"XX.XXXXXXXXX.XX",
        r".XXXXXXXXXXXXX.",
        r"XXXX.XXXXX.XXXX",
        r".XXX.XXXXX.XXX.",
        r"..XX.XXXXX.XX..",
        r".X..XX.X.XX..X.",
        r"X..X..XXX..X..X",
        r".X....XXX....X.",
        r".X..X..X..X..X.",
    ],
    "blop_baby": [
        r"..XXXX..",
        r".XXXXXX.",
        r".XXXXXX.",
        r".XX..XX.",
        r".XXXXXX.",
        r"XXXXXXXX",
        r".XXXXXX.",
        r"..X..X..",
    ],
    "blop_child": [
        r"..XX..XX..",
        r".XXXXXXXX.",
        r"XX.XXXX.XX",
        r"XXXXXXXXXX",
        r".XXXXXXXX.",
        r".XXX..XXX.",
        r".XXXXXXXX.",
        r"..XXXXXX..",
        r"...XXXX...",
    ],
    "blop_teen": [
        r"...XXXXX...",
        r"..XXXXXXX..",
        r".XXXXXXXXX.",
        r".XXX.X.XXX.",
        r".XXXXXXXXX.",
        r"XXXXXXXXXXX",
        r".XXXX.XXXX.",
        r".XXXXXXXXX.",
        r"..XXXXXXX..",
        r"..XX...XX..",
    ],
    "blop_adult": [
        r"...XXXXXX...",
        r".XXXXXXXXXX.",
        r".XXXXXXXXXX.",
        r".XX.XXXX.XX.",
        r"XXXXXXXXXXXX",
        r"XXXXXXXXXXXX",
        r".XXXXXXXXXX.",
        r".XXXXXXXXXX.",
        r"..XXXXXXXX..",
        r"..XX.XX.XX..",
        r"...XX..XX...",
    ],
    "blop_premium": [
        r"...XXXXXXXX...",
        r"..XXXXXXXXXX..",
        r".XXXXXXXXXXXX.",
        r".XXX..XX..XXX.",
        r".XXXXXXXXXXXX.",
        r"XX.XXXXXXXX.XX",
        r"XXXXXXXXXXXXXX",
        r"XX.XXXXXXXX.XX",
        r".XXXXXXXXXXXX.",
        r"..XXX....XXX..",
        r".XXXX....XXXX.",
    ],

    # === TOT & GHOST ===
    "skull": [
        r".XXXX.",
        r"X.XX.X",
        r"XXXXXX",
        r".X..X.",
        r"..XX..",
        r"..XX..",
    ],
    "ghost": [
        r"..XXXX..",
        r".XXXXXX.",
        r"XX.XX.XX",
        r"XXXXXXXX",
        r"XXX..XXX",
        r".XXXXXX.",
        r"..XXXX..",
        r"...XX...",
        r"...XX.X.",
        r"....XX..",
    ],
    "gravestone": [
        r".....X.....",
        r"....XXX....",
        r"...XXXXX...",
        r"..XXXXXXX..",
        r".XXXXXXXXX.",
        r".XXXXXXXXX.",
        r"XXXXXXXXXXX",
        r"XXXXXXXXXXX",
    ],
    "cross": [
        r"...XX...",
        r"...XX...",
        r"XXXXXXXX",
        r"XXXXXXXX",
        r"...XX...",
        r"...XX...",
        r"...XX...",
        r"...XX...",
        r"...XX...",
    ],
    "food": [
        r"X..X",
        r".XX.",
        r".XX.",
        r"X..X",
    ],
    "ball": [
        r"X.XX.X",
        r"XXXXXX",
        r"XXXXXX",
        r"X.XX.X",
    ],
    "heart": [
        r".X.X.",
        r"XXXXX",
        r"XXXXX",
        r".XXX.",
        r"..X..",
    ],
    "apple": [
        r"..X..",
        r".XXX.",
        r"XXXXX",
        r"XXXXX",
        r".XXX.",
    ],
    "sock": [
        r".XXXX",
        r".XXXX",
        r".XXXX",
        r".XXXX",
        r"XXXXX",
        r"XXXX.",
    ],

    # === WELT-DEKO ===
    "sun": [
        r"...X...",
        r".X.X.X.",
        r"..XXX..",
        r"XXXXXXX",
        r"..XXX..",
        r".X.X.X.",
        r"...X...",
    ],
    "moon": [
        r"...XX..",
        r"..XX...",
        r".XX....",
        r".XX....",
        r".XX....",
        r"..XX...",
        r"...XX..",
    ],
    "cloud": [
        r"...XXXX...",
        r".XXXXXXXX.",
        r"XXXXXXXXXX",
        r".XXXXXXXX.",
    ],
    "tree": [
        r"....X....",
        r"...XXX...",
        r"..XXXXX..",
        r".XXXXXXX.",
        r"XXXXXXXXX",
        r".XXXXXXX.",
        r"..XXXXX..",
        r"....X....",
        r"....X....",
        r"...XXX...",
    ],
    "flower": [
        r".X.X.",
        r".XXX.",
        r"..X..",
        r"..X..",
    ],
    "bowl": [
        r"X......X",
        r".XXXXXX.",
        r".XXXXXX.",
        r"..XXXX..",
    ],

    # === GEGNER (Defense-Minigame) ===
    "enemy_bug": [
        r"X.....X",
        r"XX.X.XX",
        r"XXXXXXX",
        r".X.X.X.",
        r"XXXXXXX",
        r".X...X.",
    ],
    "enemy_slime": [
        r"..XXXX..",
        r".XXXXXX.",
        r"XXXXXXXX",
        r"XX.XX.XX",
        r"XXXXXXXX",
        r".X....X.",
    ],
    "enemy_ghost": [
        r"..XXX..",
        r".XXXXX.",
        r"X.X.X.X",
        r"XXXXXXX",
        r"XXXXXXX",
        r"XXXXXXX",
        r"X.X.X.X",
    ],
    "enemy_cloud": [
        r"...XXXXX...",
        r".XXXXXXXXX.",
        r"XXXXXXXXXXX",
        r"X.XX.X.XX.X",
        r"XXXXXXXXXXX",
        r"..X..X..X..",
    ],
    "enemy_skull": [
        r".XXXXX.",
        r"XXXXXXX",
        r"X..X..X",
        r"XXXXXXX",
        r".X.X.X.",
        r".XXXXX.",
        r"..X.X..",
    ],
    "spark": [
        r".X.",
        r"XXX",
        r".X.",
    ],
    # POOP
    "poop": [
        r"...X...",
        r"..XXX..",
        r".XXXXX.",
        r"XXXXXXX",
        r".XXXXX.",
        r"..XXX..",
    ],

    # SCHMETTERLING
    "butterfly": [
        r".XX...XX.",
        r"XXXX.XXXX",
        r"XXXX.XXXX",
        r".XXX.XXX.",
        r"..X.X.X..",
    ],
    "butterfly2": [
        r"..X...X..",
        r".XX...XX.",
        r".XXX.XXX.",
        r"..XX.XX..",
        r"..X.X.X..",
    ],
    "sprout": [
        r"X...X",
        r"XX.XX",
        r".XXX.",
        r"..X..",
        r"..X..",
    ],
    "tulip": [
        r"X.X.X",
        r"XXXXX",
        r"XXXXX",
        r".XXX.",
        r"..X..",
        r".XX..",
        r"..X..",
    ],
    "mush_small": [
        r".XXX.",
        r"XX.XX",
        r"..X..",
        r"..X..",
        r"..X..",
    ],
}
